language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-webapp-java' ]; then cd .. && eval "mv $currentfolder generator-webapp-java" && cd generator-webapp-java; fi

